testcontainers:
  image: docker.io/library/golang:1.26-trixie@sha256:4ee9ffa999b4583ce281939cdff828763083610292f252279a0cee77473bd9a7
  startup_timeout: 30s
  cleanup_timeout: 30s
  ryuk_disabled: true
  ready_message: nutanix-testcontainer-ready
  command:
    - sh
    - -c
    - echo nutanix-testcontainer-ready; sleep 60
